version: '2'
services:
  proxy:
    image: cdwdpoc-proxy:latest
    ports:
     - "8080:80"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
  app:
    image: cdwdpoc-app:latest
    networks:
    - internal
networks:
  internal:
